version: '3.1'

services:
  discovery-service:
    container_name: discovery-service
    hostname: discovery-service
    build:
      context: ./discovery-service
    ports:
      - "8102:8102"
    networks:
      - backend
    healthcheck:
      test: "curl --fail --silent discovery-service:8102/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 1s
      retries: 5

  currency-exchange-service:
    build:
      context: ./currency-exchange-service
    ports:
      - "8101:8101"
    networks:
      - backend
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent currency-exchange-service:8101/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 1s
      retries: 5

  transaction-record-service_db:
    image: mongo:5.0.2
    command: mongod --port 8103
    ports:
      - "8103:8103"
    volumes:
      - "transaction-record-service_data:/data/transaction-record-service_data"
    networks:
      - backend

  transaction-record-service:
    build:
      context: ./transaction-record-service
    ports:
      - "8104:8104"
    networks:
      - backend
    depends_on:
      transaction-record-service_db:
        condition: service_started
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent transaction-record-service:8104/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 1s
      retries: 5

  telegram-bot-service:
    hostname: telegram-bot-service
    build:
      context: ./telegram-bot-service
    ports:
      - "8105:8105"
    networks:
      - backend
    depends_on:
      discovery-service:
        condition: service_healthy
      currency-exchange-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent telegram-bot-service:8105/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 1s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  transaction-record-service_data:

