version: '3.1'

services:
  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service
    ports:
      - "8102:8102"
    healthcheck:
      test: "curl --fail --silent discovery-service:8102/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 1s
      retries: 5

  currency-exchange-service:
    build:
      context: ./currency-exchange-service
    ports:
      - "8101:8101"

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - "9411:9411"

