server:
  port: 8104

spring:
  application:
    name: transaction-record-service
  data:
    mongodb:
      port: 8103
      host: transaction-record-service_db
      database: transaction-record-db
      uri: mongodb://transaction-record-service_db:8103/transaction-record-db?authSource=admin

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8102/eureka/
      links:
        - discovery-service
