server:
  port: 8102

spring:
  application:
    name: discovery-service
  profiles:
    active: prod
  config:
    import: http://config-service:8106/${spring.application.name}-${spring.profiles.active}.yml
