server:
  port: 8105

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: telegram-bot-service
  profiles:
    active: prod
  config:
    import: http://config-service:8106/${spring.application.name}-${spring.profiles.active}.yml\
