version: '3.9'

networks:
  backend:

volumes:
  transaction-record-service_data:

services:
  config-service:
    container_name: config-service
    hostname: config-service
    image: aliakseisayarkin/walty-config-service:latest
    ports:
      - "8106:8106"
    networks:
      - backend
    healthcheck:
      test: "curl --fail --silent config-service:8106/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 1s
      retries: 200

  discovery-service:
    container_name: discovery-service
    hostname: discovery-service
    image: aliakseisayarkin/walty-discovery-service:latest
    ports:
      - "8102:8102"
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent discovery-service:8102/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 1s
      retries: 200

  currency-exchange-service:
    image: aliakseisayarkin/walty-currency-exchange-service:latest
    ports:
      - "8101:8101"
    networks:
      - backend
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent currency-exchange-service:8101/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 1s
      retries: 200

  transaction-record-service_db:
    image: mongo:5.0.2
    command: mongod --port 8103
    ports:
      - "8103:8103"
    volumes:
      - "transaction-record-service_data:/data/transaction-record-service_data"
    networks:
      - backend

  transaction-record-service:
    image: aliakseisayarkin/walty-transaction-record-service:latest
    ports:
      - "8104:8104"
    networks:
      - backend
    depends_on:
      transaction-record-service_db:
        condition: service_started
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent transaction-record-service:8104/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 1s
      retries: 200

  telegram-bot-service:
    image: aliakseisayarkin/walty-telegram-bot-service:latest
    hostname: telegram-bot-service
    ports:
      - "8105:8105"
    networks:
      - backend
    depends_on:
      discovery-service:
        condition: service_healthy
      currency-exchange-service:
        condition: service_healthy
      transaction-record-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent telegram-bot-service:8105/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 1s
      retries: 200
