currency:
  integration-api-url: https://open.er-api.com/v6/latest/
  conversion-percentage-adjustment: 0.98
  rounding-scale: 4

server:
  port: 8101

spring:
  application:
    name: currency-exchange-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8102/eureka/
      links:
        - discovery-service
    enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://localhost:8101/api/v2/spans
  tracing:
    sampling:
      probability: 1