currency:
  integration-api-url: https://open.er-api.com/v6/latest/
  conversion-percentage-adjustment: 0.98
  rounding-scale: 4

server:
  port: 8101

spring:
  application:
    name: currency-exchange-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8102/eureka/
      links:
        - discovery-service