server:
  port: 8106

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/AliakseiSayarkin/walty-config-properties

management:
  endpoints:
    web:
      exposure:
        include: "*"